#!/usr/bin/python
# -*- coding: utf-8 -*-
import re
import sys
sys.path.insert(0, '/root/seongae2/TextAttack')
from textattack.commands.textattack_cli import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
